
version: '3.3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: voxdental_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./voxdental.db:/app/voxdental.db
      - ./models:/app/models
      - ./src:/app/src
    # Se recomienda .env solo para credenciales, pero docker-compose inyecta las variables también
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voxdental_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
