
version: '3.3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: suiego_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./suiego.db:/app/suiego.db
      - ./models:/app/models
      - ./src:/app/src
    # Se recomienda .env solo para credenciales, pero docker-compose inyecta las variables también
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: suiego_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
