swagger: "2.0"
info:
  description: "DNS Configuration for VoxDental"
  title: "VoxDental DNS"
  version: "1.0.0"
host: "egos.endpoints.sui-production-492623.cloud.goog"
x-google-endpoints:
- name: "egos.endpoints.sui-production-492623.cloud.goog"
  target: "35.202.203.240"
paths: {}
