swagger: "2.0"
info:
  title: "VoxDental API Gateway"
  description: "Gateway para VoxDental en Google Cloud Endpoints"
  version: "1.0.0"
host: "egos.endpoints.sui-production-492623.cloud.goog"
x-google-endpoints:
- name: "egos.endpoints.sui-production-492623.cloud.goog"
  target: "35.202.203.240"
paths:
  "/api/v1/auth/login":
    post:
      operationId: "authLogin"
      responses:
        "200":
          description: "OK"
  "/api/v1/patients":
    get:
      operationId: "listPatients"
      responses:
        "200":
          description: "OK"
    post:
      operationId: "createPatient"
      responses:
        "200":
          description: "OK"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
# Permitimos que cualquier otra ruta pase
x-google-allow: all
